In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low=1,high=100, size=20).reshape(4,5)
arr

array([[60, 83, 53, 21, 21],
       [86, 65,  9, 20, 54],
       [85, 48, 51, 74, 10],
       [ 6, 38, 60, 79, 29]])

In [3]:
arr>50

array([[ True,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [False, False,  True,  True, False]])

Indexing usinng boolean array:

In [4]:
arr[arr>50]

array([60, 83, 53, 86, 65, 54, 85, 51, 74, 60, 79])

In [7]:
arr[arr>50 & (arr%2!=0)] = 0
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
arr[arr>50 & (arr%2!=0)]
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])