In [3]:
import numpy as np
np.random.random() #will show random value from 0 to 1.

0.45975259644200095

In [4]:
np.random.seed(1)
np.random.random() #seed function will show same value always.

0.417022004702574

In [7]:
np.random.uniform(4,10) # show random values within the given values.

5.813995435791039

In [12]:
np.random.uniform(1,100,10).reshape(2,5)

array([[11.21937465, 45.34145909, 90.95095481, 30.06780069, 29.48975852],
       [13.87282864,  2.91732883, 68.20471776, 21.95118348, 27.28911928]])

In [21]:
np.random.randint(1,10,10).reshape(2,5)

array([[4, 2, 3, 8, 3],
       [7, 1, 3, 7, 7]])

In [22]:
a=np.random.randint(5,20,9)

In [23]:
a

array([ 7, 12, 12,  5, 11, 10,  6, 15,  9])

In [24]:
np.max(a)

15

In [26]:
np.sin(max(a))

0.6502878401571168

In [27]:
a[np.argmax(a)]

15

In [28]:
a[np.argmin(a)]

5

In [29]:
a=np.random.randint(5,20,6)
a

array([11,  5, 11, 10, 18,  6])

In [31]:
a[a%2==1]=-3

In [32]:
a

array([-3, -3, -3, 10, 18,  6])

In [33]:
a=np.random.randint(3,50,6)
a

array([36, 23, 13, 35, 28, 24])

In [34]:
np.where(a%2==1, -1, a)

array([36, -1, -1, -1, 28, 24])

In [35]:
a

array([36, 23, 13, 35, 28, 24])

In [36]:
a=np.random.randint(4,50,10)

In [37]:
a

array([43, 36, 23, 29, 18, 17, 24, 47, 10, 17])

In [38]:
a=np.sort(a)

In [39]:
a

array([10, 17, 17, 18, 23, 24, 29, 36, 43, 47])

In [40]:
np.percentile(a,50)

23.5

In [41]:
np.percentile(a,70)

31.099999999999998

In [42]:
np.percentile(a,98)

46.28