NameError: name 'arr4' is not defined

In [2]:
import numpy as np

In [3]:
arr4 = np.arange(6).reshape(2,3)

In [6]:
arr4

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
arr4

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
arr4

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr4.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [10]:
arr5=np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [12]:
np.hstack((arr4,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [13]:
np.vstack((arr4,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [21]:
np.vsplit(arr4,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [22]:
np.hsplit(arr4,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]