In [16]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [10]:
arr2 = np.array([[5,6,8,3],[1,7,8,3]])
arr2

array([[5, 6, 8, 3],
       [1, 7, 8, 3]])

In [12]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
arr6 = np.arange(5,16)
arr6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
arr7 = np.linspace(6,20,10)
arr7

array([ 6.        ,  7.55555556,  9.11111111, 10.66666667, 12.22222222,
       13.77777778, 15.33333333, 16.88888889, 18.44444444, 20.        ])

In [19]:
arr8 = arr5.copy()
arr8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr8.shape

(5, 5)

In [21]:
arr9 = np.array([[[1,2], [4,3]], [[4,5], [0,7]]])
arr9

array([[[1, 2],
        [4, 3]],

       [[4, 5],
        [0, 7]]])

In [22]:
arr9.shape


(2, 2, 2)

In [23]:
arr9.ndim

3

In [24]:
arr3.ndim

2

In [25]:
arr9.size

8

In [26]:
arr9.itemsize

4

In [27]:
arr8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr7

array([ 6.        ,  7.55555556,  9.11111111, 10.66666667, 12.22222222,
       13.77777778, 15.33333333, 16.88888889, 18.44444444, 20.        ])

In [29]:
arr8.itemsize

8

In [30]:
arr7.itemsize

8

In [31]:
arr2.itemsize

4

In [32]:
arr2

array([[5, 6, 8, 3],
       [1, 7, 8, 3]])

In [33]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
arr5.itemsize

8

In [36]:
arr1.itemsize

4

In [37]:
arr9

array([[[1, 2],
        [4, 3]],

       [[4, 5],
        [0, 7]]])

In [39]:
arr9.astype('float')

array([[[1., 2.],
        [4., 3.]],

       [[4., 5.],
        [0., 7.]]])

In [18]:
import numpy as np
lista = range(100)
arr11 = np.arange(100)

In [5]:
import sys

In [13]:
print(sys.getsizeof(56)*len(lista))

2800


In [19]:
print(arr11.itemsize*arr11.size)

400


In [29]:
import time
x = range (10000000)
y = range (10000000, 200000000)
start_time=time.time()
c = [(x, y) for x,y in zip(x,y)]
print(time.time()-start_time)

5.6924779415130615


In [30]:
a = np.arange(100000000)
b = np.arange(100000000, 200000000) 
start_time=time.time()
c= a+b
print(time.time()-start_time)

4.329543828964233


In [32]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
arr12[1]

array([4, 5, 6, 7])

In [53]:
arr12 [0:2, 2:4]

array([[2, 3],
       [6, 7]])

In [56]:
for i in arr12:
   print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [59]:
for i in np.nditer (arr12):
   print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
