In [1]:
import numpy as np

In [12]:
z=np.zeros(9).reshape(3,3)
z


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a=np.ones(6).reshape(2,3)
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a=np.ones(6, dtype=int).reshape(2,3)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
l=np.linspace(6, 12, 6).reshape(2,3)
l

array([[ 6. ,  7.2,  8.4],
       [ 9.6, 10.8, 12. ]])

In [30]:
l.shape

(2, 3)

In [31]:
l.ndim

2

In [32]:
l.size

6

In [33]:
l.itemsize

8

In [34]:
l.dtype

dtype('float64')

In [35]:
l.astype

<function ndarray.astype>

In [39]:
import numpy as np

# Create a NumPy array of strings representing floats
array_str = np.array(['1.2', 'Jihan', '3.8', '4.6'])

# Convert the array to floats using astype
array_float = array_str.astype(float)

print("Original array:", array_str)
print("Converted array:", array_float)


ValueError: could not convert string to float: 'Jihan'

In [40]:
for i in l:
    print (i)

[6.  7.2 8.4]
[ 9.6 10.8 12. ]


In [43]:
k=np.copy(l-1)
k

array([[ 5. ,  6.2,  7.4],
       [ 8.6,  9.8, 11. ]])

In [48]:
m=np.identity(4)
m

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
f= np.random.rand(2,2)
f

array([[0.69281987, 0.4825894 ],
       [0.75247541, 0.49661586]])

In [68]:
f= np.random.randint(2,20, 3)
f

array([ 4, 12, 13])

In [69]:
f.dtype           

dtype('int32')

In [71]:
arr=np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
arr[3:5, 2:4 ]

array([[20, 21],
       [26, 27]])

In [74]:
arr[4:6, 4:6]

array([[28, 29],
       [34, 35]])

In [76]:
for i in arr:
    print (i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]


In [77]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


In [78]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [80]:
b= np.arange(6,12)
b          

array([ 6,  7,  8,  9, 10, 11])

In [83]:
c= b-a
c

array([6, 6, 6, 6, 6, 6])

In [84]:
b-2

array([4, 5, 6, 7, 8, 9])

In [86]:
d=a*b
d

array([ 0,  7, 16, 27, 40, 55])

In [87]:
d>20

array([False, False, False,  True,  True,  True])

In [88]:
d<20

array([ True,  True,  True, False, False, False])

In [89]:
a.dot(b)

145

In [90]:
a1=np.arange(9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
b1=np.arange(9,18).reshape(3,3)
b1

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [92]:
a1.dot(b1)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [94]:
c1=np.arange(6).reshape(3,2)
c1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [97]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
a1.dot(c1)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [101]:
a1.min(axis=0) # column ways minimum values

array([0, 1, 2])

In [102]:
a1.min(axis=1) # Row ways minimum values

array([0, 3, 6])

In [103]:
a1.sum()

36

In [104]:
a1.mean()

4.0

In [105]:
np.cos(a1)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003]])

In [107]:
np.median(a1)

4.0

In [108]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])